services:
  postgres-local:
    image: timescale/timescaledb:latest-pg17
    container_name: postgres-local-eafc25
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eafc25
    ports:
      - "5432:5432"
    command: -c fsync=off -c max_prepared_transactions=10 -c shared_buffers=2500MB -c max_connections=1000 -c max_locks_per_transaction=256
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - eafc25-local-pg-volume:/var/lib/postgresql-local/data
    networks:
      - fut25_network

  postgres-mcp:
    image: crystaldba/postgres-mcp:latest
    container_name: postgres-mcp
    hostname: postgres-mcp
    ports:
      - "9432:8000"
    command: --access-mode=unrestricted --transport=sse
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@localhost:5432/eafc25
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - fut25_network

  redis:
    image: redis:7
    container_name: redis-eafc25
    ports:
      - "6379:6379"
    networks:
      - fut25_network

  celery-worker:
    build: .
    container_name: celery-worker-eafc25
    command: uv run celery -A fut_market worker -l info -Q prices
    depends_on:
      - redis
      - postgres-local
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DB_HOST=postgres-local
      - DB_NAME=eafc25
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    networks:
      - fut25_network

  celery-beat:
    build: .
    container_name: celery-beat-eafc25
    command: uv run celery -A fut_market beat -l info
    depends_on:
      - redis
      - postgres-local
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - DB_HOST=postgres-local
      - DB_NAME=eafc25
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    networks:
      - fut25_network

volumes:
  eafc25-local-pg-volume:

networks:
  fut25_network:
    driver: bridge
