global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "rules.yml"

scrape_configs:
  # Django application metrics
  - job_name: 'django'
    static_configs:
      - targets: ['localhost:8010']
    metrics_path: '/metrics/'
    scrape_interval: 10s
