"""
Django settings for fut_market project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-14x_8$l92&ylccm@#1u50@%t8a9d*gu=*f35p@-go2o#!sux)t"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "ninja",
    "core",
    "players",
    "auth_api",
    "market",
    "club",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fut_market.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fut_market.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "eafc25"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "postgres"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "TEST": {
            "NAME": "test_eafc25",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Django Ninja settings
NINJA_PAGINATION_CLASS = "ninja.pagination.LimitOffsetPagination"

# Async settings
ASGI_APPLICATION = "fut_market.asgi.application"

# Logging settings
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message} | job_id={job_id} resource_id={resource_id} error={error}",
            "style": "{",
        },
        "market_scraper": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message} | job_id={job_id} resource_id={resource_id} error={error}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "market_scraper_console": {
            "class": "logging.StreamHandler",
            "formatter": "market_scraper",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "market.scraper": {
            "handlers": ["market_scraper_console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Celery settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/1")
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_TIME_LIMIT = 60
CELERY_TASK_SOFT_TIME_LIMIT = 55
CELERY_WORKER_CONCURRENCY = int(os.getenv("CELERY_WORKER_CONCURRENCY", "2"))
CELERY_TASK_ROUTES = {
    "players.tasks.scrape_tier_prices": {"queue": "tier_{tier}"},
    "players.tasks.verify_pending_trades": {"queue": "verification"},
    "players.tasks.recalculate_player_tiers": {"queue": "maintenance"},
    "players.tasks.cleanup_expired_trades": {"queue": "maintenance"},
}

CELERY_TASK_QUEUES = {
    "tier_hot": {
        "exchange": "prices",
        "exchange_type": "direct",
        "routing_key": "tier.hot",
    },
    "tier_trending": {
        "exchange": "prices",
        "exchange_type": "direct",
        "routing_key": "tier.trending",
    },
    "tier_active": {
        "exchange": "prices",
        "exchange_type": "direct",
        "routing_key": "tier.active",
    },
    "tier_normal": {
        "exchange": "prices",
        "exchange_type": "direct",
        "routing_key": "tier.normal",
    },
    "tier_cold": {
        "exchange": "prices",
        "exchange_type": "direct",
        "routing_key": "tier.cold",
    },
    "verification": {
        "exchange": "verification",
        "exchange_type": "direct",
        "routing_key": "verification",
    },
    "maintenance": {
        "exchange": "maintenance",
        "exchange_type": "direct",
        "routing_key": "maintenance",
    },
}

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "scrape-hot-players": {
        "task": "players.tasks.scrape_tier_prices",
        "schedule": crontab(minute="*/5"),
        "kwargs": {"tier": "HOT"},
    },
    "scrape-trending-players": {
        "task": "players.tasks.scrape_tier_prices",
        "schedule": crontab(minute="*/10"),
        "kwargs": {"tier": "TRENDING"},
    },
    "scrape-active-players": {
        "task": "players.tasks.scrape_tier_prices",
        "schedule": crontab(minute="*/20"),
        "kwargs": {"tier": "ACTIVE"},
    },
    "scrape-normal-players": {
        "task": "players.tasks.scrape_tier_prices",
        "schedule": crontab(minute="*/45"),
        "kwargs": {"tier": "NORMAL"},
    },
    "scrape-cold-players": {
        "task": "players.tasks.scrape_tier_prices",
        "schedule": crontab(minute="0", hour="*/2"),
        "kwargs": {"tier": "COLD"},
    },
    "verify-trades": {
        "task": "players.tasks.verify_pending_trades",
        "schedule": crontab(minute="*/5"),
    },
    "recalculate-hotness": {
        "task": "players.tasks.recalculate_player_tiers",
        "schedule": crontab(minute="0"),
    },
    "cleanup-old-trades": {
        "task": "players.tasks.cleanup_expired_trades",
        "schedule": crontab(minute="0", hour="*/6"),
    },
}
