# Generated by Django 5.2.5 on 2025-08-10 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("timestamp", models.BigIntegerField(blank=True, null=True)),
                ("formation", models.CharField(blank=True, max_length=20, null=True)),
                ("untradeable", models.BooleanField(blank=True, null=True)),
                ("asset_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("rating", models.IntegerField(blank=True, db_index=True, null=True)),
                ("dream", models.BooleanField(blank=True, null=True)),
                ("item_type", models.CharField(blank=True, max_length=50, null=True)),
                ("resource_id", models.BigIntegerField(blank=True, null=True)),
                ("owners", models.IntegerField(blank=True, null=True)),
                ("discard_value", models.IntegerField(blank=True, null=True)),
                ("card_subtype_id", models.IntegerField(blank=True, null=True)),
                ("last_sale_price", models.IntegerField(blank=True, null=True)),
                ("injury_type", models.CharField(blank=True, max_length=50, null=True)),
                ("injury_games", models.IntegerField(blank=True, null=True)),
                ("preferred_position", models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ("stats_list", models.JSONField(blank=True, null=True)),
                ("lifetime_stats", models.JSONField(blank=True, null=True)),
                ("contract", models.IntegerField(blank=True, null=True)),
                ("team_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("rare_flag", models.IntegerField(blank=True, null=True)),
                ("play_style", models.IntegerField(blank=True, null=True)),
                ("league_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("loyalty_bonus", models.IntegerField(blank=True, null=True)),
                ("pile", models.IntegerField(blank=True, null=True)),
                ("nation", models.IntegerField(blank=True, db_index=True, null=True)),
                ("resource_game_year", models.IntegerField(blank=True, null=True)),
                ("guid_asset_id", models.UUIDField(blank=True, null=True)),
                ("attribute_array", models.JSONField(blank=True, null=True)),
                ("skill_moves", models.IntegerField(blank=True, null=True)),
                ("weak_foot_ability_type_code", models.IntegerField(blank=True, null=True)),
                ("preferred_foot", models.IntegerField(blank=True, null=True)),
                ("possible_positions", models.JSONField(blank=True, null=True)),
                ("gender", models.IntegerField(blank=True, null=True)),
                ("base_traits", models.JSONField(blank=True, null=True)),
                ("icon_traits_priorities", models.JSONField(blank=True, null=True)),
                ("icon_traits", models.JSONField(blank=True, null=True)),
                ("plus_plus_roles", models.JSONField(blank=True, null=True)),
                ("groups", models.JSONField(blank=True, null=True)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "players",
            },
        ),
        migrations.CreateModel(
            name="PlayerPriceHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("platform", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="COINS", max_length=10)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "player",
                    models.ForeignKey(
                        db_column="player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "db_table": "player_price_history",
            },
        ),
        migrations.CreateModel(
            name="PlayerPrice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("platform", models.CharField(max_length=10)),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="COINS", max_length=10)),
                ("last_updated", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "player",
                    models.ForeignKey(
                        db_column="player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "db_table": "player_prices",
                "unique_together": {("player", "platform")},
            },
        ),
    ]
