# Generated by Django 5.2.5 on 2025-08-21 07:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceScrapeJob",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Running"), ("completed", "Completed"), ("failed", "Failed")],
                        max_length=20,
                    ),
                ),
                ("total_targets", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                ("rate_limit_hits", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "price_scrape_jobs",
            },
        ),
        migrations.CreateModel(
            name="PriceScrapeFailure",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("player_id", models.BigIntegerField()),
                ("reason", models.CharField(max_length=255)),
                ("http_status", models.IntegerField(blank=True, null=True)),
                ("payload", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="players.pricescrapejob",
                    ),
                ),
            ],
            options={
                "db_table": "price_scrape_failures",
            },
        ),
    ]
