# Generated by Django 5.2.5 on 2025-08-21 13:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_pricescrapejob_pricescrapefailure"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprice",
            name="confidence_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="playerprice",
            name="last_verified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerprice",
            name="unverified_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="playerpricehistory",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerpricehistory",
            name="trade_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="PlayerTier",
            fields=[
                (
                    "player",
                    models.OneToOneField(
                        db_column="player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="tier",
                        serialize=False,
                        to="players.player",
                    ),
                ),
                ("hotness_score", models.FloatField(default=0)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("HOT", "Hot"),
                            ("TRENDING", "Trending"),
                            ("ACTIVE", "Active"),
                            ("NORMAL", "Normal"),
                            ("COLD", "Cold"),
                        ],
                        default="COLD",
                        max_length=20,
                    ),
                ),
                ("last_calculated", models.DateTimeField(default=django.utils.timezone.now)),
                ("volatility_score", models.FloatField(default=0)),
                ("volume_score", models.FloatField(default=0)),
                ("trend_score", models.FloatField(default=0)),
                ("event_score", models.FloatField(default=0)),
            ],
            options={
                "db_table": "players_playertier",
                "indexes": [models.Index(fields=["tier", "hotness_score"], name="players_pla_tier_ed96b9_idx")],
            },
        ),
        migrations.CreateModel(
            name="SessionUsage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("requests_count", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("cooldown_until", models.DateTimeField(blank=True, null=True)),
                ("is_healthy", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "scraper_sessionusage",
                "indexes": [
                    models.Index(fields=["is_healthy", "cooldown_until"], name="scraper_ses_is_heal_3809a5_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="TradeWatch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("trade_id", models.CharField(max_length=50, unique=True)),
                ("listed_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("discovered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                            ("expired", "Expired"),
                            ("active", "Active"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "player",
                    models.ForeignKey(
                        db_column="player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_watches",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "db_table": "players_tradewatch",
                "indexes": [
                    models.Index(fields=["status", "discovered_at"], name="players_tra_status_e05288_idx"),
                    models.Index(fields=["player", "status"], name="players_tra_player__324ef5_idx"),
                ],
            },
        ),
    ]
