# Generated by Django 5.2.5 on 2025-08-21 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0003_playerprice_confidence_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerprice",
            name="unverified_price",
        ),
    ]
