# Generated by Django 5.2.5 on 2025-08-21 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0004_remove_unverified_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerprice",
            name="confidence_score",
        ),
    ]
