# Generated by Django 5.2.5 on 2025-08-21 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0005_remove_confidence_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerprice",
            name="last_verified",
        ),
    ]
