# Generated by Django 5.2.5 on 2025-08-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0006_remove_last_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprice",
            name="confidence_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="playerprice",
            name="last_verified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerprice",
            name="unverified_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
