# Generated by Django 5.2.5 on 2025-08-21 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0007_add_priority_system_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerprice",
            name="confidence_score",
        ),
        migrations.RemoveField(
            model_name="playerprice",
            name="last_verified",
        ),
        migrations.RemoveField(
            model_name="playerprice",
            name="unverified_price",
        ),
    ]
