# Generated by Django 5.2.5 on 2025-08-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0008_remove_unnecessary_fields"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tradewatch",
            name="players_tra_status_e05288_idx",
        ),
        migrations.AddField(
            model_name="tradewatch",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="tradewatch",
            index=models.Index(fields=["expires_at", "status"], name="players_tra_expires_24cee4_idx"),
        ),
    ]
