# Generated by Django 5.2.5 on 2025-08-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_add_expires_at_to_tradewatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricescrapefailure',
            name='job',
        ),
        migrations.DeleteModel(
            name='SessionUsage',
        ),
        migrations.DeleteModel(
            name='PriceScrapeFailure',
        ),
        migrations.DeleteModel(
            name='PriceScrapeJob',
        ),
    ]
